travel = {'Miles Driven': None,
          '# Of Deliveries': None,
          'Time Cleaning': None,
          'Time Delivering': None,
          'Late Day Delivery': None,
          'On Call Delivery': None,
          'Overtime Hours': None}
equipment = {'IV Poles / E Car': None,
             'Suction Unit, Large Comp': None,
             'Oximeter': None,
             'Project Hear/ Cardiocom': None,
             'Wheel Chair / Enteral': None,
             'Simply Mini / Oxy Go': None,
             'Walker/Can/ ETC': None,
             'Bed': None,
             'Ultra Fill/ CPM': None,
             "ELR'S / Tanks": None,
             'Regulator': None,
             'Nebulizer': None,
             'Photo Therapy': None,
             'Simply Go/Sequal': None,
             'CPAP / BiPAP': None,
             'Knee Walker / Transport Chair': None,
             'Oxygen Set up / Portable': None,
             'Low air loss / Gel overlay /a pp': None,
             'Deroyal': None,
             'Patient Lift/Trapeze': None,
             'O2 Supply / Neb supply / PAP Supply': None,
             'Concentrator Check': None,
             'DME Assembled': None}
employees = {
    "26286": ['Aaron Williams', None],
    "23160": ['Brian Engel', None],
    "16731": ['Chelsea Short', None],
    "16504": ['Christopher Preston', None],
    "3681": ['Lance Trotter', None],
    "F162": ['Steve Reppard', None],

}
